export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';

export const GET_RES_BY_REF_REQUEST = 'GET_RES_BY_REF_REQUEST';
export const GET_RES_BY_REF_SUCCESS = 'GET_RES_BY_REF_SUCCESS';
export const GET_RES_BY_REF_FAIL = 'GET_RES_BY_REF_FAIL';

export const GET_RES_BY_DATE_REQUEST = 'GET_RES_BY_DATE_REQUEST';
export const GET_RES_BY_DATE_SUCCESS = 'GET_RES_BY_DATE_SUCCESS';
export const GET_RES_BY_DATE_FAIL = 'GET_RES_BY_DATE_FAIL';

export const GET_RES_BY_STATUS_REQUEST = 'GET_RES_BY_STATUS_REQUEST';
export const GET_RES_BY_STATUS_SUCCESS = 'GET_RES_BY_STATUS_SUCCESS';
export const GET_RES_BY_STATUS_FAIL = 'GET_RES_BY_STATUS_FAIL';

export const GET_RES_BY_ID_REQUEST = 'GET_RES_BY_ID_REQUEST';
export const GET_RES_BY_ID_SUCCESS = 'GET_RES_BY_ID_SUCCESS';
export const GET_RES_BY_ID_FAIL = 'GET_RES_BY_ID_FAIL';

export const CONFIRM_RES_REQUEST = 'CONFIRM_RES_REQUEST';
export const CONFIRM_RES_SUCCESS = 'CONFIRM_RES_SUCCESS';
export const CONFIRM_RES_FAIL = 'CONFIRM_RES_FAIL';

export const EDIT_RES_REQUEST = 'EDIT_RES_REQUEST';
export const EDIT_RES_SUCCESS = 'EDIT_RES_SUCCESS';
export const EDIT_RES_FAIL = 'EDIT_RES_FAIL';

export const DELETE_RES_REQUEST = 'DELETE_RES_REQUEST';
export const DELETE_RES_SUCCESS = 'DELETE_RES_SUCCESS';
export const DELETE_RES_FAIL = 'DELETE_RES_FAIL';
